version: "3.8"
services:
  sama-db:
    container_name: sama-db
    image: postgres:13-alpine
    command: postgres -c 'max_connections=40'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sama
      POSTGRES_USER: sama
      POSTGRES_PASSWORD: password

  sama-service:
    container_name: sama-service
    image: sama-service:latest
    ports:
      - "3001:3000"
    environment:
      X_JAVA_OPTS: |
        -Dspring.datasource.host=sama-db
        -Dspring.profiles.active=local
    volumes:
      - /var/log/sama/sama-service:/var/log/sama/sama-service
      - $HOME/.aws/credentials:/home/sama/.aws/credentials:ro

  sama-webserver:
    container_name: sama-webserver
    image: sama-webserver:latest
    ports:
      - "3000:8080"
