server:
  port: 3000
  servlet:
    context-path: /
  error:
    include-message: always  # TODO: remove for prod
    include-stacktrace: always # TODO: remove for prod

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    default: local
  datasource:
    host: localhost
    port: 5433
    database-name: sama
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database-name}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-sama.yml
  cache:
    cache-names: historical-heat-map
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=12h

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /__mon
      exposure:
        include: "*"

sentry:
  dsn: https://b8c06b0aa478447bbdc330ad9fef42f1@o877832.ingest.sentry.io/5828928
  environment: local
  traces-sample-rate: 0.0
  debug: true

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui.html

sama:
  auth.jwt:
    access:
      signing-secret: dummy-access-secret-for-development
      expiration-sec: 31536000 # 365 days
      key-id: sama-access-local
    refresh:
      signing-secret: dummy-refresh-secret-for-development
      expiration-sec: 31536000 # 365 days
      key-id: sama-refresh-local

  meeting:
    url:
      code-length: 8
      scheme: http
      host: localhost:3000

  slotsuggestion:
    heatmap:
      historical-days: 90
      historical-cache-duration-hours: 12
      future-days: 21

integration:
  google:
    client-id: 690866307711-8nm12p73mo585k5njoaqepjupgm31im3.apps.googleusercontent.com
    scopes: |
      https://www.googleapis.com/auth/calendar.events,
      https://www.googleapis.com/auth/calendar.readonly,
      https://www.googleapis.com/auth/userinfo.email,
      https://www.googleapis.com/auth/userinfo.profile
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"
  firebase:
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"