spring:
  datasource:
    host: sama-dev.cp9s2aovpufd.eu-central-1.rds.amazonaws.com
    port: 5432
    database-name: sama
    username: sama
    password: "dummy-value-this-is-loaded-from-AWS-SM"

sama:
  api.cors:
    allowed-origins: |
      http://localhost:8080,
      https://web.meetsama.com.smtest.it
  auth.jwt:
    access:
      signing-secret: "dummy-value-this-is-loaded-from-AWS-SM"
      expiration-sec: 86400 # 1 day
      key-id: sama-access-dev
    refresh:
      signing-secret: "dummy-value-this-is-loaded-from-AWS-SM"
      expiration-sec: 31536000 # 365 days
      key-id: sama-refresh-dev
  meeting:
    url:
      scheme: https
      host: web.meetsama.com.smtest.it
  landing:
    url: https://meetsama.com.smtest.it

integration:
  google:
    client-id: 690866307711-8nm12p73mo585k5njoaqepjupgm31im3.apps.googleusercontent.com
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"
  firebase:
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"

sentry:
  environment: dev
  debug: false
  traces-sample-rate: 0.3
