server:
  servlet:
    context-path: /
  port: 3000
  http2.enabled: true
  ssl.enabled: false
  shutdown: graceful
  error:
    include-message: always
    include-stacktrace: always

spring:
  application:
    name: sama-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    default: local
  datasource:
    host: localhost
    port: 5432
    database-name: sama
    username: sama
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database-name}
    hikari:
      poolName: Hikari
      minimum-idle: 10
      maximum-pool-size: 40
      connection-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 30000
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
  task:
    scheduling.pool.size: 1
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-sama.yml
    liquibase-schema: public
  cache:
    cache-names: blocks-by-user
    caffeine:
      spec: maximumSize=0

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /__mon
      server:
        request:
          autotime:
            enabled: true
      exposure:
        include:
          ['configprops', 'env', 'health', 'info', 'logfile', 'loggers', 'prometheus', 'threaddump', 'caches']
  endpoint:
    health:
      probes:
        enabled: true
  info:
    git:
      enabled: true
      mode: simple
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}

logging.level:
    org.springframework.jdbc.core: DEBUG

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui.html

sama:
  api:
    cors:
      allowed-origins: |
        *
    error:
      include-message: true
  auth.jwt:
    access:
      signing-secret: dummy-access-secret-for-development
      expiration-sec: 31536000 # 365 days
      key-id: sama-access-local
    refresh:
      signing-secret: dummy-refresh-secret-for-development
      expiration-sec: 31536000 # 365 days
      key-id: sama-refresh-local

  meeting:
    url:
      code-length: 8
      scheme: http
      host: localhost:3000
  landing:
    url: http://localhost:8080

  slotsuggestion:
    heatmap:
      interval-minutes: 15
      historical-days: 90
      historical-cache-duration-hours: 12
      future-days: 14

integration:
  google:
    client-id: 690866307711-8nm12p73mo585k5njoaqepjupgm31im3.apps.googleusercontent.com
    scopes: |
      https://www.googleapis.com/auth/calendar.events,
      https://www.googleapis.com/auth/calendar.readonly,
      https://www.googleapis.com/auth/userinfo.email,
      https://www.googleapis.com/auth/userinfo.profile
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"
    tokens.encryption:
      password: 632c851465175f96507475446996dd9b79a44a66f6205bee473f8647ab696a5b43f671da75f47f9356e945dd815e5d3cca222ff3260c9f727ae55da78614e24f
      salt: 16dc92db6028e4ec

  firebase:
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"
    api-key: "dummy-value-this-is-loaded-from-AWS-SM"
    app-link:
      api-url: "https://firebasedynamiclinks.googleapis.com/v1/shortLinks"
      fqdn: meetsamatest.page.link
      parameters:
        ibi: com.meetsama.app.dev # BundleID
        ifl: https://testflight.apple.com/join/F4cncGnA # TestFlight link (TODO: this is prod)
        isi: # AppStoreID empty for local / dev
        efr: 0 # Do not skip preview page
        ofl: https://testflight.apple.com/join/F4cncGnA # TestFlight link (TODO: this is prod)

sentry:
  dsn: https://b8c06b0aa478447bbdc330ad9fef42f1@o877832.ingest.sentry.io/5828928
  environment: local
  traces-sample-rate: 0.0
  debug: false