server:
  port: 3000
  servlet:
    context-path: /
  error:
    include-message: always  # TODO: remove for prod
    include-stacktrace: always # TODO: remove for prod

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    default: local
  datasource:
    host: localhost
    port: 5433
    database-name: sama
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database-name}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-sama.yml

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /__mon
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api/docs

sama:
  auth.jwt:
    access:
      signingSecret: dummy-access-secret-for-development
      expirationSec: 2592000 # 30 days
      keyId: dummy-access-key-id-for-development
    refresh:
      signingSecret: dummy-refresh-secret-for-development
      expirationSec: 2592000 # 30 days
      keyId: dummy-refresh-key-id-for-development

  slotsuggestion:
    heatmap:
      past-days: 90
      future-days: 21

integration:
  google:
    client-id: 690866307711-8nm12p73mo585k5njoaqepjupgm31im3.apps.googleusercontent.com
    scopes: https://www.googleapis.com/auth/calendar.readonly, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"
  firebase:
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"