server:
  error:
    include-message: never
    include-stacktrace: never

spring:
  datasource:
    host: sama-prod.cp9s2aovpufd.eu-central-1.rds.amazonaws.com
    port: 5432
    database-name: sama
    username: sama
    password: "dummy-value-this-is-loaded-from-AWS-SM"
    hikari:
      minimum-idle: 20
      maximum-pool-size: 80
  jpa:
    show-sql: false
  task:
    scheduling.pool.size: 8
  cache:
    cache-names: blocks-by-user
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=12h

logging.level:
  org.springframework.jdbc.core: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

sama:
  api:
    cors:
      allowed-origins: |
        https://web.meetsama.com,
        https://app.meetsama.com
    error:
      include-message: false
  auth.jwt:
    access:
      signing-secret: "dummy-value-this-is-loaded-from-AWS-SM"
      expiration-sec: 86400 # 1 day
      key-id: sama-access-prod
    refresh:
      signing-secret: "dummy-value-this-is-loaded-from-AWS-SM"
      expiration-sec: 31536000 # 365 days
      key-id: sama-refresh-prod
  meeting:
    url:
      scheme: https
      host: app.meetsama.com
  landing:
    url: https://meetsama.com

integration:
  google:
    client-id: 706689065341-qouatnct20253qe10ti6k265qh6p7vm0.apps.googleusercontent.com
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"
    tokens.encryption:
      password: # Loaded from AWS SM
      salt: # Loaded from AWS SM
    sync:
      channel:
        enabled: true
        callback-url: https://app.meetsama.com/api/integration/google/channel-notification

  firebase:
    credentials: "dummy-value-this-is-loaded-from-AWS-SM"
    api-key: "dummy-value-this-is-loaded-from-AWS-SM"
    app-link:
      fqdn: meetsama.page.link
      parameters:
        ibi: com.meetsama.sama # BundleID
        ifl: # Overrides `isi` if specified
        isi: 1586527998 # AppStore ID
        efr: 0 # Do not skip preview page
        ofl: https://apps.apple.com/lt/app/sama-scheduling-assistant/id1586527998

sentry:
  environment: prod
  debug: false
  traces-sample-rate: 0.3
