spring:
  datasource:
    host: sama-dev.cp9s2aovpufd.eu-central-1.rds.amazonaws.com
    port: 5432
    database-name: sama
    username: sama
    password: "dummy-value-this-is-loaded-from-AWS-SM"

sama:
  meeting:
    url:
      scheme: https
      host: app.yoursama.com
