spring:
  datasource:
    host: sama-dev.cp9s2aovpufd.eu-central-1.rds.amazonaws.com
    port: 5432
    database-name: sama
    username: sama
    password: "dummy-value-this-is-loaded-from-AWS-SM"

sama:
  auth.jwt:
    access:
      signing-secret: "dummy-value-this-is-loaded-from-AWS-SM"
      expiration-sec: 86400 # 1 day
      key-id: sama-access-dev
    refresh:
      signing-secret: "dummy-value-this-is-loaded-from-AWS-SM"
      expiration-sec: 31536000 # 365 days
      key-id: sama-refresh-dev
  meeting:
    url:
      scheme: https
      host: app.meetsama.com.smtest.it

sentry:
  dsn: https://b8c06b0aa478447bbdc330ad9fef42f1@o877832.ingest.sentry.io/5828928
  environment: dev
  debug: false
  traces-sample-rate: 0.3
