databaseChangeLog:
  - changeSet:
      id: add-user-settings
      author: balys
      changes:
        - createTable:
            schemaName: sama
            tableName: user_settings
            columns:
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: PK_user_settings_user_id
              - column:
                  name: locale
                  type: VARCHAR
              - column:
                  name: timezone
                  type: VARCHAR
              - column:
                  name: format_24_hour_time
                  type: BOOL
              - column:
                  constraints:
                    nullable: false
                  name: updated_at
                  type: TIMESTAMP

        - addForeignKeyConstraint:
            baseTableSchemaName: sama
            baseTableName: user_settings
            baseColumnNames: user_id
            constraintName: FK_user_settings_user_id
            referencedTableSchemaName: sama
            referencedTableName: user
            referencedColumnNames: id
            onDelete: CASCADE

        - createTable:
            schemaName: sama
            tableName: user_day_working_hours
            columns:
              - column:
                  name: id
                  type: SERIAL
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: PK_user_day_working_hours_id
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: day_of_week
                  type: smallint
                  constraints:
                    nullable: false
              - column:
                  name: start_time
                  type: time
                  constraints:
                    nullable: false
              - column:
                  name: end_time
                  type: time
                  constraints:
                    nullable: false

        - addForeignKeyConstraint:
            baseTableSchemaName: sama
            baseTableName: user_day_working_hours
            baseColumnNames: user_id
            constraintName: FK_user_day_working_hours_user_id
            referencedTableSchemaName: sama
            referencedTableName: user_settings
            referencedColumnNames: user_id
            onDelete: CASCADE

        - addUniqueConstraint:
            schemaName: sama
            tableName: user_day_working_hours
            columnNames: user_id, day_of_week
            constraintName: UQ_user_day_working_hours_day_of_week


  # Separate changeset because addCheckConstraint required Liquibase Pro.
  - changeSet:
      id: add-day-working-hours_constraint
      author: balys
      changes:
        - sql:
            sql: ALTER TABLE sama.user_day_working_hours ADD CONSTRAINT CK_user_day_working_hour_day_of_week
              CHECK (day_of_week >=0 AND day_of_week <= 6)
      rollback:
        - sql:
            sql: ALTER TABLE sama.user_day_working_hours DROP CONSTRAINT CK_user_day_working_hour_day_of_week




