name: dev

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: make container

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Upload to ECR
        run: make upload-to-ecr

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Init Terraform
        run: make dev-terraform-init

      - name: Validate Terraform
        run: make terraform-validate

      - name: Get Current Deployment Colour
        id: current_deployment
        run: echo ::set-output name=COLOUR::$(make dev-current-deployment)

      - name: Deploy
        run: make dev-deploy

      - name: Undeploy Blue
        run: make dev-destroy-blue
        if: steps.current_deployment.outputs.COLOUR == 'blue'

      - name: Undeploy Green
        run: make dev-destroy-green
        if: steps.current_deployment.outputs.COLOUR == 'green'