name: Update release notes

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}